{{- $namespace := .Values.root.namespace }}
{{- range .Values.applications }}
{{ if .enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  project: default
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
    {{ if .valuesFile }}
    helm:
      values: |-
       {{- $.Files.Get .valuesFile | nindent 7 -}}
    {{ end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace={{ .createNamespace }}
{{ end }}
{{- end }}
